export default {
  "name": "Governor's Ball",
  "location": "Randall's Island, NYC",
  "timezone": -5,
  "artists": [
    "ACTION BRONSON",
    "AGAINST ME!",
    "ALBERT HAMMOND JR.",
    "BAT FOR LASHES",
    "BECK",
    "BETTY WHO",
    "BIG GRAMS",
    "BLACK PISTOL FIRE",
    "BLANK RANGE",
    "BLOC PARTY",
    "BOB MOSES",
    "BOOGIE",
    "BULLY",
    "CATFISH AND THE BOTTLEMEN",
    "CHET FAKER",
    "CHRISTINE AND THE QUEENS",
    "CHVRCHES",
    "COLD WAR KIDS",
    "COURTNEY BARNETT",
    "DAY WAVE",
    "DE LA SOUL",
    "DEATH CAB FOR CUTIE",
    "DUKE DUMONT",
    "EAGLES OF DEATH METAL",
    "ELIOT SUMNER",
    "ELLE KING",
    "FATHER JOHN MISTY",
    "FIDLAR",
    "GALANTIS",
    "GARY CLARK JR.",
    "HAIM",
    "HOLLY MIRANDA",
    "JAMIE XX",
    "JOEY BADA$$",
    "JON BELLION",
    "KANYE WEST",
    "LORD HURON",
    "LOUIS THE CHILD",
    "M83",
    "MAC MILLER",
    "MARIAN HILL",
    "MATT AND KIM",
    "MEG MAC",
    "MIGUEL",
    "MIIKE SNOW",
    "MISTERWIVES",
    "NOTHING",
    "OF MONSTERS AND MEN",
    "PUBLIC ACCESS T.V.",
    "PURITY RING",
    "ROBYN",
    "SPECIAL GUEST",
    "THE KILLERS",
    "THE KNOCKS",
    "THE LONDON SOULS",
    "THE STROKES",
    "THOMAS JACK",
    "THUNDERCAT",
    "TOR MILLER",
    "TORRES",
    "TRANSVIOLET",
    "TWO DOOR CINEMA CLUB",
    "VIC MENSA",
    "VINCE STAPLES",
    "WHILK & MISKY",
    "WHITNEY",
    "YEARS & YEARS"
  ],
  "stages": [
    "bacardi_house",
    "big_apple",
    "govball_nyc",
    "honda"
  ],
  "schedule": [{
    "date": "06/03/2016",
    "events": [{"artist":"BLOC PARTY","start_time":{"hour":20,"min":0},"end_time":{"hour":21,"min":15},"stage":"big_apple"},{"artist":"FATHER JOHN MISTY","start_time":{"hour":17,"min":45},"end_time":{"hour":18,"min":45},"stage":"big_apple"},{"artist":"BULLY","start_time":{"hour":14,"min":15},"end_time":{"hour":15,"min":0},"stage":"big_apple"},{"artist":"PUBLIC ACCESS T.V.","start_time":{"hour":12,"min":45},"end_time":{"hour":13,"min":30},"stage":"big_apple"},{"artist":"ACTION BRONSON","start_time":{"hour":15,"min":45},"end_time":{"hour":16,"min":45},"stage":"big_apple"},{"artist":"THE STROKES","start_time":{"hour":21,"min":15},"end_time":{"hour":23,"min":0},"stage":"govball_nyc"},{"artist":"BECK","start_time":{"hour":18,"min":45},"end_time":{"hour":20,"min":0},"stage":"govball_nyc"},{"artist":"OF MONSTERS AND MEN","start_time":{"hour":16,"min":45},"end_time":{"hour":17,"min":45},"stage":"govball_nyc"},{"artist":"CHRISTINE AND THE QUEENS","start_time":{"hour":15,"min":0},"end_time":{"hour":15,"min":45},"stage":"govball_nyc"},{"artist":"ELLE KING","start_time":{"hour":13,"min":30},"end_time":{"hour":14,"min":15},"stage":"govball_nyc"},{"artist":"THE LONDON SOULS","start_time":{"hour":12,"min":15},"end_time":{"hour":12,"min":45},"stage":"govball_nyc"},{"artist":"JAMIE XX","start_time":{"hour":20,"min":0},"end_time":{"hour":21,"min":15},"stage":"bacardi_house"},{"artist":"DUKE DUMONT","start_time":{"hour":17,"min":45},"end_time":{"hour":18,"min":45},"stage":"bacardi_house"},{"artist":"BOB MOSES","start_time":{"hour":15,"min":45},"end_time":{"hour":16,"min":45},"stage":"bacardi_house"},{"artist":"BOOGIE","start_time":{"hour":14,"min":15},"end_time":{"hour":15,"min":0},"stage":"bacardi_house"},{"artist":"BLACK PISTOL FIRE","start_time":{"hour":12,"min":45},"end_time":{"hour":13,"min":30},"stage":"bacardi_house"},{"artist":"ROBYN","start_time":{"hour":21,"min":15},"end_time":{"hour":23,"min":0},"stage":"honda"},{"artist":"MATT AND KIM","start_time":{"hour":19,"min":0},"end_time":{"hour":20,"min":0},"stage":"honda"},{"artist":"BIG GRAMS","start_time":{"hour":16,"min":45},"end_time":{"hour":17,"min":45},"stage":"honda"},{"artist":"YEARS & YEARS","start_time":{"hour":15,"min":0},"end_time":{"hour":15,"min":45},"stage":"honda"},{"artist":"MEG MAC","start_time":{"hour":13,"min":30},"end_time":{"hour":14,"min":15},"stage":"honda"},{"artist":"TRANSVIOLET","start_time":{"hour":12,"min":15},"end_time":{"hour":12,"min":45},"stage":"honda"}]
  }, {
    "date": "06/04/2016",
    "events": [{"artist":"DE LA SOUL","start_time":{"hour":17,"min":45},"end_time":{"hour":18,"min":45},"stage":"big_apple"},{"artist":"MIIKE SNOW","start_time":{"hour":20,"min":0},"end_time":{"hour":21,"min":15},"stage":"big_apple"},{"artist":"MISTERWIVES","start_time":{"hour":15,"min":45},"end_time":{"hour":16,"min":45},"stage":"big_apple"},{"artist":"JON BELLION","start_time":{"hour":14,"min":15},"end_time":{"hour":15,"min":0},"stage":"big_apple"},{"artist":"NOTHING","start_time":{"hour":12,"min":45},"end_time":{"hour":13,"min":30},"stage":"big_apple"},{"artist":"THE KILLERS","start_time":{"hour":21,"min":15},"end_time":{"hour":23,"min":0},"stage":"govball_nyc"},{"artist":"HAIM","start_time":{"hour":18,"min":45},"end_time":{"hour":20,"min":0},"stage":"govball_nyc"},{"artist":"LORD HURON","start_time":{"hour":16,"min":45},"end_time":{"hour":17,"min":45},"stage":"govball_nyc"},{"artist":"CATFISH AND THE BOTTLEMEN","start_time":{"hour":15,"min":0},"end_time":{"hour":15,"min":45},"stage":"govball_nyc"},{"artist":"MARIAN HILL","start_time":{"hour":13,"min":30},"end_time":{"hour":14,"min":15},"stage":"govball_nyc"},{"artist":"ELIOT SUMNER","start_time":{"hour":12,"min":15},"end_time":{"hour":12,"min":45},"stage":"govball_nyc"},{"artist":"PURITY RING","start_time":{"hour":20,"min":15},"end_time":{"hour":21,"min":15},"stage":"bacardi_house"},{"artist":"AGAINST ME!","start_time":{"hour":17,"min":45},"end_time":{"hour":18,"min":45},"stage":"bacardi_house"},{"artist":"THUNDERCAT","start_time":{"hour":15,"min":45},"end_time":{"hour":16,"min":45},"stage":"bacardi_house"},{"artist":"THE KNOCKS","start_time":{"hour":14,"min":15},"end_time":{"hour":15,"min":0},"stage":"bacardi_house"},{"artist":"LOUIS THE CHILD","start_time":{"hour":12,"min":45},"end_time":{"hour":13,"min":30},"stage":"bacardi_house"},{"artist":"M83","start_time":{"hour":21,"min":15},"end_time":{"hour":23,"min":0},"stage":"honda"},{"artist":"MIGUEL","start_time":{"hour":18,"min":45},"end_time":{"hour":20,"min":0},"stage":"honda"},{"artist":"MAC MILLER","start_time":{"hour":16,"min":45},"end_time":{"hour":17,"min":45},"stage":"honda"},{"artist":"ALBERT HAMMOND JR.","start_time":{"hour":15,"min":0},"end_time":{"hour":15,"min":45},"stage":"honda"},{"artist":"TORRES","start_time":{"hour":13,"min":30},"end_time":{"hour":14,"min":15},"stage":"honda"},{"artist":"HOLLY MIRANDA","start_time":{"hour":12,"min":15},"end_time":{"hour":12,"min":45},"stage":"honda"}]
  }, {
    "date": "06/05/2016",
    "events": [{"artist":"CHET FAKER","start_time":{"hour":20,"min":0},"end_time":{"hour":21,"min":15},"stage":"big_apple"},{"artist":"COURTNEY BARNETT","start_time":{"hour":17,"min":25},"end_time":{"hour":18,"min":25},"stage":"big_apple"},{"artist":"EAGLES OF DEATH METAL","start_time":{"hour":15,"min":25},"end_time":{"hour":16,"min":25},"stage":"big_apple"},{"artist":"FIDLAR","start_time":{"hour":13,"min":55},"end_time":{"hour":14,"min":40},"stage":"big_apple"},{"artist":"WHITNEY","start_time":{"hour":12,"min":25},"end_time":{"hour":13,"min":10},"stage":"big_apple"},{"artist":"KANYE WEST","start_time":{"hour":21,"min":15},"end_time":{"hour":23,"min":0},"stage":"govball_nyc"},{"artist":"CHVRCHES","start_time":{"hour":16,"min":25},"end_time":{"hour":17,"min":25},"stage":"govball_nyc"},{"artist":"TWO DOOR CINEMA CLUB","start_time":{"hour":19,"min":0},"end_time":{"hour":20,"min":5},"stage":"govball_nyc"},{"artist":"COLD WAR KIDS","start_time":{"hour":14,"min":40},"end_time":{"hour":15,"min":25},"stage":"govball_nyc"},{"artist":"BETTY WHO","start_time":{"hour":13,"min":10},"end_time":{"hour":13,"min":55},"stage":"govball_nyc"},{"artist":"TOR MILLER","start_time":{"hour":23,"min":55},"end_time":{"hour":12,"min":25},"stage":"govball_nyc"},{"artist":"THOMAS JACK","start_time":{"hour":20,"min":5},"end_time":{"hour":21,"min":15},"stage":"bacardi_house"},{"artist":"GALANTIS","start_time":{"hour":17,"min":25},"end_time":{"hour":18,"min":25},"stage":"bacardi_house"},{"artist":"VIC MENSA","start_time":{"hour":15,"min":25},"end_time":{"hour":16,"min":25},"stage":"bacardi_house"},{"artist":"BAT FOR LASHES","start_time":{"hour":13,"min":55},"end_time":{"hour":14,"min":40},"stage":"bacardi_house"},{"artist":"DAY WAVE","start_time":{"hour":12,"min":25},"end_time":{"hour":13,"min":10},"stage":"bacardi_house"},{"artist":"SPECIAL GUEST","start_time":{"hour":18,"min":30},"end_time":{"hour":19,"min":0},"stage":"bacardi_house"},{"artist":"DEATH CAB FOR CUTIE","start_time":{"hour":21,"min":15},"end_time":{"hour":23,"min":0},"stage":"honda"},{"artist":"GARY CLARK JR.","start_time":{"hour":18,"min":50},"end_time":{"hour":20,"min":0},"stage":"honda"},{"artist":"JOEY BADA$$","start_time":{"hour":16,"min":25},"end_time":{"hour":17,"min":25},"stage":"honda"},{"artist":"VINCE STAPLES","start_time":{"hour":14,"min":40},"end_time":{"hour":15,"min":25},"stage":"honda"},{"artist":"WHILK & MISKY","start_time":{"hour":13,"min":10},"end_time":{"hour":13,"min":55},"stage":"honda"},{"artist":"BLANK RANGE","start_time":{"hour":23,"min":55},"end_time":{"hour":12,"min":25},"stage":"honda"}]
  }]
};
